=== bethoven01/eApp/src/test/resources/testdata/Responses/scenario2/API_ResponseSchema4.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/Welcome2",
    "definitions": {
        "Welcome2": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "messageid": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "subject": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                }
            },
            "required": [
                "description",
                "email",
                "messageid",
                "name",
                "phone",
                "subject"
            ],
            "title": "Welcome2"
        }
    }
}

=== bethoven01/eApp/src/test/resources/testdata/Responses/scenario2/API_Response4.json
{"messageid":2,"name":"Gaurav Khandelwal","email":"gkhandelwal3@gmail.com","phone":"918767867687687","subject":"TEST Case 1 TEST Case 1 TEST Case 1 TEST Case 1 TEST Case 1 ","description":"TEST Case 1 TEST Case 1 TEST Case 1 TEST Case 1 TEST Case 1 TEST Case 1 TEST Case 1 TEST Case 1 TEST Case 1 TEST Case 1 TEST Case 1 TEST Case 1 TEST Case 1 TEST Case 1 TEST Case 1 TEST Case 1 "}
